config/routes.rb
MissionControl::Servers::Engine.routes.draw do
  resources :projects do
    resources :public_projects, except: [:edit, :update]
    resources :service_settings, only: [:edit, :update]
    resource :ingress, only: :create
    resource :script, only: :show
    namespace :dashboards do
      resource :project_table, only: :show
      resource :cpu_usage, only: :show
      resource :memory_usage, only: :show
      resource :disk_free, only: :show
      resource :last_seen, only: :show
      resource :cpu_history, only: :show
      resource :memory_history, only: :show
      resource :combo_history, only: :show
      resource :request_total, only: :show
      resource :request_chart, only: :show
    end
  end
  root to: "projects#index"
end

app/models/mission_control/servers/application_record.rb
module MissionControl
  module Servers
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/mission_control/servers/project.rb
module MissionControl::Servers
  class Project < ApplicationRecord
    has_many :services, dependent: :destroy
    has_many :requests, dependent: :destroy
    has_many :service_settings, dependent: :destroy
    has_many :public_projects, dependent: :destroy
    has_secure_token :token
  end
end

app/models/mission_control/servers/public_project.rb
module MissionControl::Servers
  class PublicProject < ApplicationRecord
    belongs_to :project
    has_secure_token :token, length: 128
  end
end

app/models/mission_control/servers/request.rb
module MissionControl::Servers
  class Request < ApplicationRecord
    belongs_to :project
    after_create :trim_old_requests

    class << self
      def recent_totals(project, hostname)
        recent_requests(project, hostname)
      end

      def recent_requests(project, hostname)
        where(
          hostname: [service_setting(project, hostname), hostname].compact.uniq,
          created_at: 1.minute.ago..
        )
      end

      def service_setting(project, hostname)
        project.service_settings.find_by(hostname: hostname)&.request_hostname
      end
    end

    private

      def trim_old_requests
        project.requests.where(hostname: hostname).where(created_at: ..1.hour.ago).delete_all
      end
  end
end

app/models/mission_control/servers/service.rb
module MissionControl::Servers
  class Service < ApplicationRecord
    belongs_to :project
    after_create :trim_old_records
    before_create :set_hostname

    scope :ordered, -> { order(created_at: :desc) }

    class << self
      def combo_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        cpu_usages = []
        memory_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_cpu_service = relevant_services.max_by(&:cpu)
          max_memory_service = relevant_services.max_by do |service|
            return 0 if service.mem_used.to_f + service.mem_free.to_f == 0.0
            service.mem_used.to_f / (service.mem_used.to_f + service.mem_free.to_f)
          end
          cpu_usages << (max_cpu_service&.cpu || 0).to_f
          if max_memory_service
            total_memory = max_memory_service.mem_used.to_f + max_memory_service.mem_free.to_f
            percentage_memory_used = (max_memory_service.mem_used.to_f / total_memory) * 100
            memory_usages << percentage_memory_used.to_i
          else
            memory_usages << 0.0
          end
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        data = [
          {
            label: 'CPU Usage',
            data: cpu_usages,
            fill: true,
            borderColor: "rgb(54, 162, 235)",
            tension: 0.25
          },
          {
            label: 'Memory Usage',
            data: memory_usages,
            fill: true,
            borderColor: "rgb(235, 127, 54)",
            tension: 0.25
          }
        ]
        { created_at_times: created_at_times, data: data }
      end


      def cpu_usage_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        cpu_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_cpu_service = relevant_services.max_by(&:cpu)
          cpu_usages << (max_cpu_service&.cpu || 0).to_f
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        { cpu_usages: cpu_usages, created_at_times: created_at_times }
      end


      def memory_usage_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        memory_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_memory_service = relevant_services.max_by(&:mem_used)
          memory_usages << (max_memory_service&.mem_used || 0).to_f
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        { memory_usages: memory_usages, created_at_times: created_at_times }
      end
    end

    def mem_percent
      return 0 if mem_used.to_f + mem_free.to_f == 0.0
      (mem_used.to_f / (mem_used.to_f + mem_free.to_f) * 100).to_i
    end

    private

    def trim_old_records
      project.services.where(hostname: hostname).where(created_at: ..1.week.ago).delete_all
    end

    def set_hostname
      self.hostname ||= "unnamed server"
    end
  end
end

app/models/mission_control/servers/service_setting.rb
module MissionControl::Servers
  class ServiceSetting < ApplicationRecord
    belongs_to :project
    before_create :set_request_hostname

    private

    def set_request_hostname
      self.request_hostname ||= hostname
    end
  end
end

app/controllers/mission_control/servers/application_controller.rb
module MissionControl
  module Servers
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/mission_control/servers/dashboards/combo_histories_controller.rb
module MissionControl::Servers
  class Dashboards::ComboHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @combo_history_data = MissionControl::Servers::Service.combo_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/cpu_histories_controller.rb
module MissionControl::Servers
  class Dashboards::CpuHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @cpu_history_data = MissionControl::Servers::Service.cpu_usage_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/cpu_usages_controller.rb
module MissionControl::Servers
  class Dashboards::CpuUsagesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/disk_frees_controller.rb
module MissionControl::Servers
  class Dashboards::DiskFreesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/last_seens_controller.rb
module MissionControl::Servers
  class Dashboards::LastSeensController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/memory_histories_controller.rb
module MissionControl::Servers
  class Dashboards::MemoryHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @memory_history_data = MissionControl::Servers::Service.memory_usage_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/memory_usages_controller.rb
module MissionControl::Servers
  class Dashboards::MemoryUsagesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/project_tables_controller.rb
module MissionControl::Servers
  class Dashboards::ProjectTablesController < ApplicationController
    def show
      @project = Project.includes(:services).find_by(token: params[:project_id])
      @service_settings = @project.service_settings
    end
  end
end

app/controllers/mission_control/servers/dashboards/request_charts_controller.rb
module MissionControl::Servers
  class Dashboards::RequestChartsController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      recent_requests = @project.requests.recent_totals(@project, @hostname)
      @summary_hash = {
        sum_2xx: recent_requests.sum(:sum_2xx).to_i,
        sum_3xx: recent_requests.sum(:sum_3xx).to_i,
        sum_4xx: recent_requests.sum(:sum_4xx).to_i,
        sum_5xx: recent_requests.sum(:sum_5xx).to_i,
        unknown: recent_requests.sum(:unknown).to_i
      }
    end
  end
end

app/controllers/mission_control/servers/dashboards/request_totals_controller.rb
module MissionControl::Servers
  class Dashboards::RequestTotalsController < ApplicationController
    def show
      @project = Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      recent_requests = @project.requests.recent_totals(@project, @hostname)
      @total_sum = recent_requests.sum(:sum_2xx).to_i +
        recent_requests.sum(:sum_3xx).to_i +
        recent_requests.sum(:sum_4xx).to_i +
        recent_requests.sum(:sum_5xx).to_i +
        recent_requests.sum(:unknown).to_i

    end
  end
end

app/controllers/mission_control/servers/ingresses_controller.rb
module MissionControl::Servers
  class IngressesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_project

    def create
      ingress = @project.services.new(ingress_params)
      request = @project.requests.new(tally_params)
      if ingress.save && request.save
        head :ok
      else
        head :unprocessable_entity
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find_by!(token: params[:project_id])
      end

      def ingress_params
        params.require(:service).permit(:hostname, :cpu, :mem_used, :mem_free, :disk_free)
      end

      def tally_params
        params.require(:tally).permit(:hostname, :'sum_2xx', :'sum_3xx', :'sum_4xx', :'sum_5xx', :unknown)
      end
  end
end

app/controllers/mission_control/servers/projects_controller.rb
module MissionControl::Servers
  class ProjectsController < ApplicationController
    before_action :set_project, only: %i[ show edit update destroy ]
    before_action :verify_single_project_mode, only: %i[ new create ]

    # GET /projects
    def index
      @projects = Project.all
    end

    # GET /projects/1
    def show
      hostnames = @project.services.pluck(:hostname).uniq
      @service_settings = @project.service_settings.where(hostname: hostnames)
      @services = if params[:hostname]
        @project.services.where(hostname: params[:hostname]).group_by(&:hostname)
      else
        @project.services.group_by(&:hostname)
      end
    end

    # GET /projects/new
    def new
      @project = Project.new
    end

    # GET /projects/1/edit
    def edit
    end

    # POST /projects
    def create
      @project = Project.new(project_params)

      if @project.save
        redirect_to @project, notice: "Project was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /projects/1
    def update
      if @project.update(project_params)
        redirect_to @project, notice: "Project was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /projects/1
    def destroy
      if params[:hostname]
        @project.services.where(hostname: params[:hostname]).delete_all
        redirect_to project_dashboards_project_table_path(@project.token), notice: "Service was successfully destroyed.", status: :see_other
      else
        @project.destroy!
        redirect_to projects_url, notice: "Project was successfully destroyed.", status: :see_other
      end
    end

    private
      def verify_single_project_mode
        if MissionControl::Servers.configuration.single_project_mode && Project.any?
          redirect_to projects_url, notice: "Single project mode is enabled. You can only have one project at a time."
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.includes(:services, :service_settings).find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def project_params
        params.require(:project).permit(:title, :token)
      end
  end
end

app/controllers/mission_control/servers/public_projects_controller.rb
module MissionControl::Servers
  class PublicProjectsController < ApplicationController
    before_action :set_project

    # GET /public_projects
    def index
      @public_projects = @project.public_projects.all
    end

    # GET /public_projects/1
    def show
      @project.public_projects.find_by!(token: params[:id])

      hostnames = @project.services.pluck(:hostname).uniq
      @service_settings = @project.service_settings.where(hostname: hostnames)
      @services = if params[:hostname]
        @project.services.where(hostname: params[:hostname]).group_by(&:hostname)
      else
        @project.services.group_by(&:hostname)
      end
    end

    # GET /public_projects/new
    def new
      @public_project = @project.public_projects.new
    end

    # POST /public_projects
    def create
      @public_project = @project.public_projects.new(public_project_params)

      if @public_project.save
        redirect_to project_public_projects_path(@project), notice: "Public project was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # DELETE /public_projects/1
    def destroy
      @public_project = @project.public_projects.find(params[:id])
      @public_project.destroy!
      redirect_to project_public_projects_path(@project), notice: "Public project was successfully destroyed.", status: :see_other
    end

    private
      def set_project
        @project = Project.find(params[:project_id])
      end

      # Only allow a list of trusted parameters through.
      def public_project_params
        params.require(:public_project).permit(:name)
      end
  end
end

app/views/mission_control/servers/projects/_form.html.erb
<%= form_with(model: project, class: "max-w-lg mx-auto my-10") do |form| %>
  <% if project.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Oops!</strong>
      <span class="block sm:inline"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</span>
      <ul class="list-disc list-inside mt-2">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit class: "btn btn-primary btn-block" %>
    <%= link_to "Cancel", project, class: "text-gray-light px-4 transition duration-150 ease-in-out" %>
  </div>
<% end %>

app/views/mission_control/servers/projects/_panels.html.erb
<%= tag.div id: [hostname, "tab-content"].join("-"), class: "py-4 sm:py-8 tab-content", "data-target": hostname, "data-tabs-target": "content" do %>
  <div class="mx-auto  px-6 lg:px-8">
    <div class="mx-auto  lg:max-w-none">
      <dl class="grid grid-cols-1 gap-0.5 overflow-hidden rounded-2xl text-center sm:grid-cols-2 lg:grid-cols-6">
        <%= turbo_frame_tag dom_id(project, [hostname, :cpu_usage].join('-')),
          src: project_dashboards_cpu_usage_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_cpu_usage_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 30000 %>

        <%= turbo_frame_tag dom_id(project, [hostname, :memory_usage].join('-')),
          src: project_dashboards_memory_usage_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_memory_usage_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 30000 %>

        <%= turbo_frame_tag dom_id(project, [hostname, :disk_free].join('-')),
          src: project_dashboards_disk_free_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_disk_free_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 60000 %>

        <%= turbo_frame_tag dom_id(project, [hostname, :last_seen].join('-')),
          src: project_dashboards_last_seen_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_last_seen_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 60000 %>

        <%= turbo_frame_tag dom_id(project, [hostname, :request_total].join('-')),
          src: project_dashboards_request_total_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_request_total_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 60000 %>

        <%= turbo_frame_tag dom_id(project, [hostname, :request_chart].join('-')),
          src: project_dashboards_request_chart_path(project_id: project.token, hostname: hostname),
          "data-controller": "refresh",
          "data-refresh-src-value": project_dashboards_request_chart_path(project_id: project.token, hostname: hostname),
          "data-refresh-interval-value": 60000 %>
      </dl>
      <% if params[:combo] == "false" %>
        <dl class="mt-8 grid grid-cols-1 gap-0.5 overflow-hidden rounded-2xl text-center sm:grid-cols-1 lg:grid-cols-2">
          <%= turbo_frame_tag dom_id(project, [hostname, :cpu_history].join('-')),
            src: project_dashboards_cpu_history_path(project_id: project.token, hostname: hostname),
            "data-controller": "refresh",
            "data-refresh-src-value": project_dashboards_cpu_history_path(project_id: project.token, hostname: hostname),
            "data-refresh-interval-value": 60000 %>
          <%= turbo_frame_tag dom_id(project, [hostname, :memory_history].join('-')),
            src: project_dashboards_memory_history_path(project_id: project.token, hostname: hostname),
            "data-controller": "refresh",
            "data-refresh-src-value": project_dashboards_memory_history_path(project_id: project.token, hostname: hostname),
            "data-refresh-interval-value": 60000 %>
        </dl>
      <% else %>
        <dl class="mt-8 grid grid-cols-1 gap-0.5 overflow-hidden rounded-2xl text-center sm:grid-cols-1 lg:grid-cols-1">
          <%= turbo_frame_tag dom_id(project, [hostname, :combo_history].join('-')),
            src: project_dashboards_combo_history_path(project_id: project.token, hostname: hostname),
            "data-controller": "refresh",
            "data-refresh-src-value": project_dashboards_combo_history_path(project_id: project.token, hostname: hostname),
            "data-refresh-interval-value": 60000 %>
        </dl>
      <% end %>
    </div>
  </div>
<% end %>

app/views/mission_control/servers/projects/_tabs.html.erb
<div class="mt-3">
  <nav class="isolate flex divide-x divide-gray-200 dark:divide-gray-500 rounded-lg shadow" aria-label="Tabs">
    <% services.each_with_index do |(hostname, services), index| %>
      <% first_tab_class = index.zero? ? "rounded-l-lg" : "" %>
      <% last_tab_class = index == services.length - 1 ? "rounded-r-lg" : "" %>
      <%= tag.a "#",
        "data-action": "click->tabs#changeTab",
        "data-target": hostname,
        "data-tabs-target": "link",
        class: "tab-link flex items-center justify-center #{first_tab_class} #{last_tab_class}" do %>
        <% service_setting = service_settings.find { |s| s.hostname == hostname } %>
        <% if service_setting %>
          <%= service_setting.label %>
        <% else %>
          <%= hostname %>
        <% end %>
      <% end %>
    <% end %>
  </nav>
</div>

app/views/mission_control/servers/projects/edit.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1"></div>
  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <span class="hidden sm:block">
      <button data-controller="dark-mode" data-action="click->dark-mode#toggle" class="btn btn-default">Dark Mode</button>
    </span>
  </div>
</div>

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 my-10">
  <h1 class="text-2xl text-center font-semibold text-gray-normal mb-8">Editing project</h1>

  <%= render "form", project: @project %>

  <div class="text-center mt-6">
    <%= link_to "Back to projects", projects_path, class: "text-gray-light px-4 transition duration-150 ease-in-out" %>
  </div>
</div>

app/views/mission_control/servers/projects/index.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1"></div>
  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <span class="hidden sm:block">
      <button data-controller="dark-mode" data-action="click->dark-mode#toggle" class="btn btn-default">Dark Mode</button>
    </span>
  </div>
</div>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Projects</h1>
      <p class="mt-2 text-sm text-gray-normal">Resource monitor for your Ruby on Rails applications.</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <% if allowed_to_create_project? %>
        <%= link_to "New project", new_project_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle">
        <table class="min-w-full divide-y divide-gray-300">
          <tbody class="divide-y divide-gray-200">
            <% @projects.each do |project| %>
              <tr>
                <td class="whitespace-nowrap text-2xl font-bold tracking-tight text-gray-normal sm:text-3xl"><%= project.title %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 lg:pr-8">
                  <span data-controller="dialog">
                    <%= link_to "Public Links", project_public_projects_path(project), "data-action": "click->dialog#show", "data-turbo-frame": "public_links", class: "btn btn-default" %>
                    <div data-dialog-target="modal" class="hidden fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
                      <div data-action="click->dialog#hide" class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
                      <div class="flex items-end justify-center min-h-full p-4 text-center sm:items-center">
                        <div class="relative bg-white dark:bg-gray-900 rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 md:max-w-3xl sm:w-full">
                          <div class="px-4 pt-5 pb-4 sm:p-6">
                            <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">Public Links</h3>
                            <div class="mt-2">
                              <p class="text-sm text-gray-light">
                                <%= turbo_frame_tag :public_links %>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </span>
                  <%= link_to "Dashboards", project, target: :_top, class: "btn btn-default" %>
                  <%= link_to "Remove", project, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class: "btn btn-danger" %>
                </td>
              </tr>
              <tr>
                <td colspan=2>
                  <%= turbo_frame_tag dom_id(project, "table"),
                    src: project_dashboards_project_table_path(project.token),
                    "data-controller": "refresh",
                    "data-refresh-src-value": project_dashboards_project_table_path(project.token),
                    "data-refresh-interval-value": 60000 %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/mission_control/servers/projects/new.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1"></div>
  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <span class="hidden sm:block">
      <button data-controller="dark-mode" data-action="click->dark-mode#toggle" class="btn btn-default">Dark Mode</button>
    </span>
  </div>
</div>

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 my-10">
  <h1 class="text-2xl text-center font-semibold text-gray-normal mb-8">New Project</h1>

  <%= render "form", project: @project %>

  <div class="text-center mt-6">
    <%= link_to "Back to projects", projects_path, class: "text-gray-light transition duration-150 ease-in-out" %>
  </div>
</div>

app/views/mission_control/servers/projects/show.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight"><%= @project.title %></h2>
  </div>

  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <span class="hidden sm:block">
      <button data-controller="dark-mode" data-action="click->dark-mode#toggle" class="btn btn-default">Dark Mode</button>

      <%= link_to edit_project_path(@project), class: "btn btn-default" do %>
        Edit
      <% end %>
      <%= link_to projects_path, class: "btn btn-default" do %>Projects<% end %>

      <span data-controller="dialog copy">
        <button data-action="click->dialog#show" class="btn btn-primary-subtle">
          Deploy
        </button>
        <div data-dialog-target="modal" class="hidden fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
          <div data-action="click->dialog#hide" class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
          <div class="flex items-end justify-center min-h-full p-4 text-center sm:items-center">
            <div class="relative bg-white dark:bg-gray-900 rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 md:max-w-3xl sm:w-full">
              <div class="px-4 pt-5 pb-4 sm:p-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">Installation Instructions</h3>
                <div class="mt-2">
                  <p class="text-sm text-gray-light">
                    You'll make a cURL request from each server that you want to monitor.
                    Copy and paste the script below to each server to start sending metrics to your dashboard.
                  </p>
                  <button data-action="click->copy#copy" class="rounded-md bg-blue-500 mt-4 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-600">
                    Copy
                  </button>
                    <pre data-copy-target="source" class="bg-gray-700 text-white p-4 mt-4 text-sm overflow-x-auto">curl -sSL <%= project_script_url(@project.token) %> | sh</pre>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </span>

    </span>
  </div>
</div>
<% interval = params[:interval].present? ? params[:interval].to_i * 1000 : 10_000 %>
<%= tag.div data: { controller: "tabs", "tabs-refresh-interval-value": interval } do %>
  <%= render partial: "mission_control/servers/projects/tabs",
        locals: {
          services: @services,
          service_settings: @service_settings
        } %>
  <% @services.each do |hostname, _services| %>
    <%= render partial: "mission_control/servers/projects/panels", locals: { project: @project, hostname: hostname } %>
  <% end %>
<% end %>