config/routes.rb
MissionControl::Servers::Engine.routes.draw do
  resources :projects do
    resources :public_projects, except: [:edit, :update]
    resources :service_settings, only: [:edit, :update]
    resource :ingress, only: :create
    resource :script, only: :show
    namespace :dashboards do
      resource :project_table, only: :show
      resource :cpu_usage, only: :show
      resource :memory_usage, only: :show
      resource :disk_free, only: :show
      resource :last_seen, only: :show
      resource :cpu_history, only: :show
      resource :memory_history, only: :show
      resource :combo_history, only: :show
      resource :request_total, only: :show
      resource :request_chart, only: :show
    end
  end
  root to: "projects#index"
end

app/models/mission_control/servers/application_record.rb
module MissionControl
  module Servers
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/mission_control/servers/project.rb
module MissionControl::Servers
  class Project < ApplicationRecord
    has_many :services, dependent: :destroy
    has_many :requests, dependent: :destroy
    has_many :service_settings, dependent: :destroy
    has_many :public_projects, dependent: :destroy
    has_secure_token :token
  end
end

app/models/mission_control/servers/public_project.rb
module MissionControl::Servers
  class PublicProject < ApplicationRecord
    belongs_to :project
    has_secure_token :token, length: 128
  end
end

app/models/mission_control/servers/request.rb
module MissionControl::Servers
  class Request < ApplicationRecord
    belongs_to :project
    after_create :trim_old_requests

    class << self
      def recent_totals(project, hostname)
        recent_requests(project, hostname)
      end

      def recent_requests(project, hostname)
        where(
          hostname: [service_setting(project, hostname), hostname].compact.uniq,
          created_at: 1.minute.ago..
        )
      end

      def service_setting(project, hostname)
        project.service_settings.find_by(hostname: hostname)&.request_hostname
      end
    end

    private

      def trim_old_requests
        project.requests.where(hostname: hostname).where(created_at: ..1.hour.ago).delete_all
      end
  end
end

app/models/mission_control/servers/service.rb
module MissionControl::Servers
  class Service < ApplicationRecord
    belongs_to :project
    after_create :trim_old_records
    before_create :set_hostname

    scope :ordered, -> { order(created_at: :desc) }

    class << self
      def combo_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        cpu_usages = []
        memory_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_cpu_service = relevant_services.max_by(&:cpu)
          max_memory_service = relevant_services.max_by do |service|
            return 0 if service.mem_used.to_f + service.mem_free.to_f == 0.0
            service.mem_used.to_f / (service.mem_used.to_f + service.mem_free.to_f)
          end
          cpu_usages << (max_cpu_service&.cpu || 0).to_f
          if max_memory_service
            total_memory = max_memory_service.mem_used.to_f + max_memory_service.mem_free.to_f
            percentage_memory_used = (max_memory_service.mem_used.to_f / total_memory) * 100
            memory_usages << percentage_memory_used.to_i
          else
            memory_usages << 0.0
          end
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        data = [
          {
            label: 'CPU Usage',
            data: cpu_usages,
            fill: true,
            borderColor: "rgb(54, 162, 235)",
            tension: 0.25
          },
          {
            label: 'Memory Usage',
            data: memory_usages,
            fill: true,
            borderColor: "rgb(235, 127, 54)",
            tension: 0.25
          }
        ]
        { created_at_times: created_at_times, data: data }
      end


      def cpu_usage_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        cpu_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_cpu_service = relevant_services.max_by(&:cpu)
          cpu_usages << (max_cpu_service&.cpu || 0).to_f
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        { cpu_usages: cpu_usages, created_at_times: created_at_times }
      end


      def memory_usage_history(services, start_time: 1.hour.ago, end_time: Time.now.utc)
        timestamps = (start_time.to_i..end_time.to_i).step(60).map { |t| Time.at(t).utc.change(sec: 0).to_i }
        grouped_services = services.group_by { |service| service.created_at.utc.change(sec: 0).to_i }

        memory_usages = []
        created_at_times = []

        timestamps.each do |timestamp|
          relevant_services = grouped_services[timestamp] || []
          max_memory_service = relevant_services.max_by(&:mem_used)
          memory_usages << (max_memory_service&.mem_used || 0).to_f
          created_at_times << Time.at(timestamp).utc.strftime('%H:%M%p')
        end

        { memory_usages: memory_usages, created_at_times: created_at_times }
      end
    end

    def mem_percent
      return 0 if mem_used.to_f + mem_free.to_f == 0.0
      (mem_used.to_f / (mem_used.to_f + mem_free.to_f) * 100).to_i
    end

    private

    def trim_old_records
      project.services.where(hostname: hostname).where(created_at: ..1.week.ago).delete_all
    end

    def set_hostname
      self.hostname ||= "unnamed server"
    end
  end
end

app/models/mission_control/servers/service_setting.rb
module MissionControl::Servers
  class ServiceSetting < ApplicationRecord
    belongs_to :project
    before_create :set_request_hostname

    private

    def set_request_hostname
      self.request_hostname ||= hostname
    end
  end
end

app/controllers/mission_control/servers/application_controller.rb
module MissionControl
  module Servers
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/mission_control/servers/dashboards/combo_histories_controller.rb
module MissionControl::Servers
  class Dashboards::ComboHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @combo_history_data = MissionControl::Servers::Service.combo_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/cpu_histories_controller.rb
module MissionControl::Servers
  class Dashboards::CpuHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @cpu_history_data = MissionControl::Servers::Service.cpu_usage_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/cpu_usages_controller.rb
module MissionControl::Servers
  class Dashboards::CpuUsagesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/disk_frees_controller.rb
module MissionControl::Servers
  class Dashboards::DiskFreesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/last_seens_controller.rb
module MissionControl::Servers
  class Dashboards::LastSeensController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/memory_histories_controller.rb
module MissionControl::Servers
  class Dashboards::MemoryHistoriesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      services = @project.services.where(hostname: @hostname).ordered
      @memory_history_data = MissionControl::Servers::Service.memory_usage_history(services)
    end
  end
end

app/controllers/mission_control/servers/dashboards/memory_usages_controller.rb
module MissionControl::Servers
  class Dashboards::MemoryUsagesController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      @service = @project.services.where(hostname: @hostname).last
    end
  end
end

app/controllers/mission_control/servers/dashboards/project_tables_controller.rb
module MissionControl::Servers
  class Dashboards::ProjectTablesController < ApplicationController
    def show
      @project = Project.includes(:services).find_by(token: params[:project_id])
      @service_settings = @project.service_settings
    end
  end
end

app/controllers/mission_control/servers/dashboards/request_charts_controller.rb
module MissionControl::Servers
  class Dashboards::RequestChartsController < ApplicationController
    def show
      @project = MissionControl::Servers::Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      recent_requests = @project.requests.recent_totals(@project, @hostname)
      @summary_hash = {
        sum_2xx: recent_requests.sum(:sum_2xx).to_i,
        sum_3xx: recent_requests.sum(:sum_3xx).to_i,
        sum_4xx: recent_requests.sum(:sum_4xx).to_i,
        sum_5xx: recent_requests.sum(:sum_5xx).to_i,
        unknown: recent_requests.sum(:unknown).to_i
      }
    end
  end
end

app/controllers/mission_control/servers/dashboards/request_totals_controller.rb
module MissionControl::Servers
  class Dashboards::RequestTotalsController < ApplicationController
    def show
      @project = Project.find_by(token: params[:project_id])
      @hostname = params[:hostname]
      recent_requests = @project.requests.recent_totals(@project, @hostname)
      @total_sum = recent_requests.sum(:sum_2xx).to_i +
        recent_requests.sum(:sum_3xx).to_i +
        recent_requests.sum(:sum_4xx).to_i +
        recent_requests.sum(:sum_5xx).to_i +
        recent_requests.sum(:unknown).to_i

    end
  end
end

app/controllers/mission_control/servers/ingresses_controller.rb
module MissionControl::Servers
  class IngressesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_project

    def create
      ingress = @project.services.new(ingress_params)
      request = @project.requests.new(tally_params)
      if ingress.save && request.save
        head :ok
      else
        head :unprocessable_entity
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find_by!(token: params[:project_id])
      end

      def ingress_params
        params.require(:service).permit(:hostname, :cpu, :mem_used, :mem_free, :disk_free)
      end

      def tally_params
        params.require(:tally).permit(:hostname, :'sum_2xx', :'sum_3xx', :'sum_4xx', :'sum_5xx', :unknown)
      end
  end
end

app/controllers/mission_control/servers/projects_controller.rb
module MissionControl::Servers
  class ProjectsController < ApplicationController
    before_action :set_project, only: %i[ show edit update destroy ]
    before_action :verify_single_project_mode, only: %i[ new create ]

    # GET /projects
    def index
      @projects = Project.all
    end

    # GET /projects/1
    def show
      hostnames = @project.services.pluck(:hostname).uniq
      @service_settings = @project.service_settings.where(hostname: hostnames)
      @services = if params[:hostname]
        @project.services.where(hostname: params[:hostname]).group_by(&:hostname)
      else
        @project.services.group_by(&:hostname)
      end
    end

    # GET /projects/new
    def new
      @project = Project.new
    end

    # GET /projects/1/edit
    def edit
    end

    # POST /projects
    def create
      @project = Project.new(project_params)

      if @project.save
        redirect_to @project, notice: "Project was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /projects/1
    def update
      if @project.update(project_params)
        redirect_to @project, notice: "Project was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /projects/1
    def destroy
      if params[:hostname]
        @project.services.where(hostname: params[:hostname]).delete_all
        redirect_to project_dashboards_project_table_path(@project.token), notice: "Service was successfully destroyed.", status: :see_other
      else
        @project.destroy!
        redirect_to projects_url, notice: "Project was successfully destroyed.", status: :see_other
      end
    end

    private
      def verify_single_project_mode
        if MissionControl::Servers.configuration.single_project_mode && Project.any?
          redirect_to projects_url, notice: "Single project mode is enabled. You can only have one project at a time."
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.includes(:services, :service_settings).find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def project_params
        params.require(:project).permit(:title, :token)
      end
  end
end

app/controllers/mission_control/servers/public_projects_controller.rb
module MissionControl::Servers
  class PublicProjectsController < ApplicationController
    before_action :set_project

    # GET /public_projects
    def index
      @public_projects = @project.public_projects.all
    end

    # GET /public_projects/1
    def show
      @project.public_projects.find_by!(token: params[:id])

      hostnames = @project.services.pluck(:hostname).uniq
      @service_settings = @project.service_settings.where(hostname: hostnames)
      @services = if params[:hostname]
        @project.services.where(hostname: params[:hostname]).group_by(&:hostname)
      else
        @project.services.group_by(&:hostname)
      end
    end

    # GET /public_projects/new
    def new
      @public_project = @project.public_projects.new
    end

    # POST /public_projects
    def create
      @public_project = @project.public_projects.new(public_project_params)

      if @public_project.save
        redirect_to project_public_projects_path(@project), notice: "Public project was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # DELETE /public_projects/1
    def destroy
      @public_project = @project.public_projects.find(params[:id])
      @public_project.destroy!
      redirect_to project_public_projects_path(@project), notice: "Public project was successfully destroyed.", status: :see_other
    end

    private
      def set_project
        @project = Project.find(params[:project_id])
      end

      # Only allow a list of trusted parameters through.
      def public_project_params
        params.require(:public_project).permit(:name)
      end
  end
end

app/views/mission_control/servers/public_projects/_form.html.erb
<%= form_with model: [project, public_project] do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit class: "btn btn-primary btn-block" %>
    <%= link_to "Cancel", project_public_projects_path(project), class: "text-gray-light px-4 transition duration-150 ease-in-out" %>
  </div>
<% end %>

app/views/mission_control/servers/public_projects/edit.html.erb
<%= turbo_frame_tag :public_links do %>

<h1>Editing public project</h1>

<%= render "form", public_project: @public_project %>

<br>

<div>
  <%= link_to "Show this public project", @public_project %> |
  <%= link_to "Back to public projects", public_projects_path %>
</div>
<% end %>

app/views/mission_control/servers/public_projects/index.html.erb
<%= turbo_frame_tag :public_links do %>
  <div data-controller="url-maker">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <%= check_box_tag "dark", "true", false, data: { action: "change->url-maker#updateLink", url_maker_target: "dark" }, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
        Dark Mode
      </div>
      <div class="sm:flex-auto">
        <%= check_box_tag "combo", "false", false, data: { action: "change->url-maker#updateLink", url_maker_target: "combo" }, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
        Disable Combo Chart
      </div>
      <div class="sm:flex-auto">
        <%= text_field_tag "interval", "10", data: { action: "input->url-maker#updateLink", url_maker_target: "interval" }, class: "w-20 border-1 bg-transparent py-1.5 pl-1 text-gray-900 dark:text-gray-100 placeholder:text-gray-400 focus:ring-1 sm:text-sm sm:leading-6" %>
        Tab Interval
      </div>
      <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
        <%= link_to "New Public Link", new_project_public_project_path(@project), class: "btn btn-primary" %>
      </div>
    </div>
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-normal sm:pl-6">Name</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
            <span class="sr-only">Select</span>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @public_projects.each do |public_project| %>
          <tr>
            <td class="relative py-4 pl-4 pr-3 text-sm sm:pl-6">
              <div class="font-medium text-gray-normal">
                <%= public_project.name %>
              </div>
            </td>
            <td class="relative py-3.5 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
              <div class="flex items-center justify-end space-x-2"> <!-- Flex container with space between items -->
                <div data-controller="copy">
                  <%= link_to "PUBLIC LINK", project_public_project_url(@project, id: public_project.token), "data-url-maker-target": "link", class: "hidden" %>
                  <div data-action="click->copy#copy" class="btn btn-default">Public Link</div>
                  <span data-copy-target="source" class="hidden" data-url-maker-target="output">
                    link
                  </span>
                </div>
                <%= link_to "Remove", project_public_project_path(@project, public_project), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class: "btn btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/mission_control/servers/public_projects/new.html.erb
<%= turbo_frame_tag :public_links do %>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 my-10">
    <%= render "form", project: @project, public_project: @public_project %>
  </div>
<% end %>

app/views/mission_control/servers/public_projects/show.html.erb
<div class="lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight"><%= @project.title %></h2>
  </div>

  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <span class="hidden sm:block">
      <button data-controller="dark-mode" data-action="click->dark-mode#toggle" class="btn btn-default">Dark Mode</button>
    </span>
  </div>
</div>
<% interval = params[:interval].present? ? params[:interval].to_i * 1000 : 10_000 %>
<%= tag.div data: { controller: "tabs", "tabs-refresh-interval-value": interval } do %>
  <%= render partial: "mission_control/servers/projects/tabs",
        locals: {
          services: @services,
          service_settings: @service_settings
        } %>
  <% @services.each do |hostname, _services| %>
    <%= render partial: "mission_control/servers/projects/panels", locals: { project: @project, hostname: hostname } %>
  <% end %>
<% end %>